config/routes.rb
ProbSet3::Application.routes.draw do

  resources :seats

  root :to => "users#home"

  resources :users

  resources :chats do
    resources :messages
  end
  resource :session

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  validates :position, :uniqueness => true

  belongs_to :user

  def place
    if position
      "Row #{position/8 + 1} Seat Number #{position%8}"
    else
      "Have not pick a seat yet!"
    end
  end

  def claimed_by?(claimer)
    return false unless claimer.is_a? User
    user == claimer
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_filter :authenticate, :except => [:show, :index]

  # GET /seats
  # GET /seats.xml
  def index
    @seats = Seat.order("position").all
    if @seats.count == 0
      for i in 1..32
        @seat = Seat.create(:position => i)
      end
      redirect_to seats_path
    else
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @seats }
      end
    end
  end

  # GET /seats/1
  # GET /seats/1.xml
  def show
    redirect = false
    @seat = Seat.find_by_position(params[:id])
    if @seat.nil?
      redirect = true
    end
    respond_to do |format|
      if redirect == true
        format.html { redirect_to(seats_path,  :notice => 'Seat does not exist in class, sorry') }
      else
        format.html # show.html.erb
        format.xml  { render :xml => @seat }
      end
    end
  end

  # PUT /seats/1
  # PUT /seats/1.xml
  def update
    @seat = Seat.find_by_position(params[:id])
    @user = current_user
    old_seat = 
    respond_to do |format|
        if @seat.user.nil?
          @user.seat = @seat
          format.html { redirect_to(@seat, :notice => 'Seat was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { redirect_to(seats_path, :notice => 'Seat is already taken!') }        
        end
    end
  end

end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= submit_or_cancel(f, "Take Seat", "Back to Seating Chart") %>
  </div>
<% end %>

app/views/seats/index.html.erb
<h1 class="center">Seating Chart</h1>
<% if @seats %>
<div class="seat">
Front of class
</div>
<table class="seat">
  <% for i in 0..3 %>
    <tr> 
      <% for j in 0..7%>
        <% if j == 4%><td></td><% end %>
          <% if @seats[i*7+j+i].user.nil? %>
            <td><%= link_to "Empty Seat", @seats[i*7+j+i] %> </td>
          <%else %>
            <td><%= link_to "#{@seats[i*7+j+i].user.email}", @seats[i*7+j+i] %> </td>
          <% end %>
      <% end %>
    </tr>
  <% end %>
</table>
<div class="seat">
Back of class
</div>
<% end %>
<br />

app/views/seats/show.html.erb
<% if @seat.user %>
  <p>
    <strong>User:</strong>
    <%= link_to "#{@seat.user.email}", user_path(@seat.user) %>
  </p>
  <p>
    <strong>Position:</strong>
    <%= @seat.place %>
  </p>
  <br/>
  <% if not @seat.claimed_by? current_user %>
  <%= link_to "Chat with #{@seat.user.email}", new_chat_path(:id => @seat.user.id)%> | 
  <% end %>
  <%= link_to 'Back to Seating Chart', seats_path %>
<% else %>
  <p>
    <strong>User:</strong>
    <em>This seat is open!!</em>
  </p>
  <p>
    <strong>Position:</strong>
    <%= @seat.place %>
  </p>
  
  <% if current_user %>
    <%= render "form" %>
  <% else %>
    <br/>
    <%= link_to 'Back to Seating Chart', seats_path %>
  <% end %>
  <br/>
<% end %>