config/routes.rb
ProbSet3::Application.routes.draw do

  resources :seats

  root :to => "users#home"

  resources :users

  resources :chats do
    resources :messages
  end
  resource :session

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password

  validates :email, :uniqueness => true, 
                    :length => { :within => 5..50 },
                    :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
  validates :password, :confirmation => true, 
                       :length => { :within => 4..20 },
                       :presence => true, 
                       :if => :password_required?
  has_one :profile
  has_one :seat
  has_many :messages
  has_and_belongs_to_many :chats

  def self.find_everyone(user)
    if not user.nil?
      self.find(:all, :conditions => ["id NOT IN (?)", user.id])
    end
  end

  before_save :encrypt_new_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
  def encrypt_new_password
    return if password.blank?
    self.hashed_password = encrypt(password)
  end
 
  def password_required?
    hashed_password.blank? || password.present?
  end
 
  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]

  def index
    @user = current_user
    @users = User.find_everyone(@user)
  end

  def home
    if current_user
      @user = current_user
      @chats = @user.chats
      render :action => 'show'
    else
      @seats = Seat.order("position").all
      if @seats.count == 0
        for i in 1..32
          @seat = Seat.create(:position => i)
        end

        redirect_to root_path
      else
        render :action=> 'seats/index'
      end
    end
  end

  def show
    begin 
      if params[:id]
        @user = User.find(params[:id])
      else
        @user = current_user
        @chats = @user.chats
      end
    rescue
      redirect_to users_path, :notice => 'No such user'
    end
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(user_path(@user), :notice => 'User successfully added.')
    else
      render :action => 'new'
    end
  end

  def edit
    authenticate
    @user = current_user
  end
 
  def update
    authenticate
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to(user_path(@user), :notice => 'Update user information successfully.')
    else
      render :action => 'edit'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
    <% end %>
   </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users to chat with</h1>
<% if @users %>
<ul>
<% @users.each do |user| %>
  <li><%= link_to "#{user.email}", new_chat_path(:id => user.id) %></li>
<% end %>
</ul>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to'Back', users_path %>

app/views/users/show.html.erb
<h1><% if @user == current_user %>Your Home<% else %>User # <%= @user.id %><% end %></h1>

<div>
email: <%= @user.email %> <%if @user == current_user %><%= link_to "change email?", edit_user_path(current_user) %><% end %>
</div>

<div>
sitting: 
     <% if @user.seat %>
       <%= @user.seat.place %> <% if @user == current_user %><%= link_to "change seats?", seats_path %><% end %>
     <% else %>
      up in the clouds <% if @user == current_user %><%= link_to "Pick a seats?", seats_path %><% end %>
     <% end %>
</div>
<% if @user == current_user %>
  <%= link_to 'Start Chatting?', chats_path %> 
  <% if @user.chats.count > 0 %>
   <h3>Your Past Chats</h3>
   <ul>
   <% @user.chats.each do |chat| %>
     <li>
       <%= link_to "#{chat.time}", chat_path(chat) %> 
       <% if chat.users.count > 1 %>
       with
       <% chat.users.each do |user| %>
         <% if user != current_user %>
           <%= user.email %>
         <% end %>
       <% end %>
       <% end %>
     </li>
   <% end %>
   </ul>
  <% end %>
<% end %>